<?php
/**
 * Handles the early plugin prohibition token before the rest of the plugin loads.
 *
 * @package AI_For_SEO
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Returns the transient name for a one-time plugin prohibition token.
 *
 * @param string $token One-time token.
 * @return string Transient name.
 */
function ai4seo_get_prohibit_plugin_token_transient_name( string $token ): string {
	return 'ai4seo_prohibit_plugin_token_' . hash( 'sha256', $token );
}


/**
 * Returns the current request URL for matching a prohibit token to its intended target.
 *
 * @return string Current absolute URL.
 */
function ai4seo_get_current_prohibit_plugin_request_url(): string {
	// Build from server values because the full plugin URL helpers are not loaded before this early-exit branch.
	$https       = isset( $_SERVER['HTTPS'] ) ? sanitize_text_field( wp_unslash( $_SERVER['HTTPS'] ) ) : '';
	$host_raw    = '';
	$request_uri = isset( $_SERVER['REQUEST_URI'] ) ? esc_url_raw( wp_unslash( $_SERVER['REQUEST_URI'] ), array( 'http', 'https' ) ) : '';
	$scheme      = ( '' !== $https && 'off' !== strtolower( $https ) ) ? 'https' : 'http';

	if ( isset( $_SERVER['HTTP_HOST'] ) ) {
		$host_raw = sanitize_text_field( wp_unslash( $_SERVER['HTTP_HOST'] ) );
	} elseif ( isset( $_SERVER['SERVER_NAME'] ) ) {
		$host_raw = sanitize_text_field( wp_unslash( $_SERVER['SERVER_NAME'] ) );
	}

	$host = preg_replace( '/[^A-Za-z0-9.:\-\[\]]/', '', $host_raw );

	if ( '' === $host || '' === $request_uri || '/' !== $request_uri[0] ) {
		return '';
	}

	// Sanitize the reconstructed absolute URL for internal comparison while preserving encoded path/query values.
	return esc_url_raw( $scheme . '://' . $host . $request_uri, array( 'http', 'https' ) );
}


/**
 * Normalizes a URL for comparing the current request with the token's target URL.
 *
 * @param string $url URL to normalize.
 * @return string Normalized URL.
 */
function ai4seo_normalize_prohibit_plugin_target_url( string $url ): string {
	// Compare target URLs without the one-time query token while preserving the remaining request shape.
	$url   = remove_query_arg( 'ai4seo_prohibit_plugin_token', $url );
	$parts = wp_parse_url( $url );

	if ( ! is_array( $parts ) || empty( $parts['scheme'] ) || empty( $parts['host'] ) ) {
		return '';
	}

	// Rebuild only the URL parts that identify the intended request target.
	$normalized_url  = strtolower( (string) $parts['scheme'] ) . '://' . strtolower( (string) $parts['host'] );
	$normalized_url .= isset( $parts['port'] ) ? ':' . (int) $parts['port'] : '';
	$normalized_url .= isset( $parts['path'] ) ? (string) $parts['path'] : '/';
	$normalized_url .= ! empty( $parts['query'] ) ? '?' . (string) $parts['query'] : '';

	return esc_url_raw( $normalized_url, array( 'http', 'https' ) );
}


/**
 * Checks whether the current request matches the target URL stored for a prohibit token.
 *
 * @param string $target_url Token target URL.
 * @return bool Whether the token may apply to this request.
 */
function ai4seo_current_request_matches_prohibit_plugin_target( string $target_url ): bool {
	if ( '' === $target_url ) {
		return false;
	}

	// Normalize both URLs through the same path before consuming the one-time token.
	$current_url = ai4seo_normalize_prohibit_plugin_target_url( ai4seo_get_current_prohibit_plugin_request_url() );
	$target_url  = ai4seo_normalize_prohibit_plugin_target_url( $target_url );

	return '' !== $current_url && $current_url === $target_url;
}


/**
 * Checks and consumes the early plugin prohibition token for the current request.
 *
 * @return bool Whether the main plugin loader should stop before loading normal modules.
 */
function ai4seo_should_prohibit_plugin(): bool {
	// Continue loading when the request carries no one-time prohibition token.
	// phpcs:ignore WordPress.Security.NonceVerification.Recommended -- One-time debug tokens are generated by a nonce-protected admin form.
	if ( ! isset( $_GET['ai4seo_prohibit_plugin_token'] ) ) {
		return false;
	}

	// phpcs:ignore WordPress.Security.NonceVerification.Recommended -- One-time debug tokens are generated by a nonce-protected admin form.
	$ai4seo_prohibit_plugin_token = sanitize_text_field( wp_unslash( $_GET['ai4seo_prohibit_plugin_token'] ) );

	if ( '' === $ai4seo_prohibit_plugin_token ) {
		return false;
	}

	// The transient binds a generated token to exactly one target URL and is consumed on a valid match.
	$ai4seo_prohibit_plugin_token_transient = ai4seo_get_prohibit_plugin_token_transient_name( $ai4seo_prohibit_plugin_token );
	$ai4seo_prohibit_plugin_target_url      = get_transient( $ai4seo_prohibit_plugin_token_transient );

	if ( ! is_string( $ai4seo_prohibit_plugin_target_url ) || ! ai4seo_current_request_matches_prohibit_plugin_target( $ai4seo_prohibit_plugin_target_url ) ) {
		return false;
	}

	delete_transient( $ai4seo_prohibit_plugin_token_transient );

	return true;
}
